version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  backend:
    depends_on:
      - dynamodb-local
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      DYNAMODB_TABLE_NAME: 'products'
      DYNAMODB_ENDPOINT_URL: 'http://dynamodb-local:8000'
      DYNAMODB_REGION: 'us-west-2' # or any other region you prefer
    volumes:
    - ./backend:/app
    # networks:
    #   - woocommerce-example-shop_default

# networks:
#   woocommerce-example-shop_default:
#     external: true